CREATE DATABASE IF NOT EXISTS med_manager DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE med_manager;
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),email VARCHAR(100) UNIQUE,password VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS medicines(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),lot VARCHAR(50),expiry_date DATE,quantity INT,user_id INT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
INSERT INTO users(name,email,password) VALUES ('Admin','admin@example.com','$2y$10$29jaMP0t/rD.5vHrG.lx/OqXzC2qZxc3i.ks8eX7Yx8uHm4qCdc6i');
